### PR TITLE
Added download directory to make get_url idempotent

### PR DESCRIPTION
**Pull request by drzow**
Good day! Thank you for the great work you have put up for using Ansible for a number of great security tools. I am using this for some deployment work I am doing and made this quick fix to make the maxmind deployment idempotent. Some might dislike keeping the original compressed files around, but I figure the space is worth it for a clean deploy. I might have other tweaks as I work through some of the other tools; feel free to let me know if you are not interested and I can just keep them on my own fork.

Thanks!
Terry

### CODE REVIEW

**Comment by juju4** [comment]
Hello Terry,
You are welcomed for the roles.
It seems even if test completed successfully, not totally good for idempotence (download marked changed and extract failed). creates issue?
https://travis-ci.org/juju4/ansible-maxmind/jobs/358562778#L2310

Can you review? I will try to have a look later this week or week-end.

Thanks

**Comment by drzow** [comment]
Ah-ha -- I took the success at face value without considering that the idempotency test would essentially be commented out, so I updated that as well.
The difficult thing here is that I do not see the same behaviour when running locally. I thought maybe it was an ansible change, so I rolled back to 2.5.0 (I have been running from master) and that did not help. In the get_url task I see (one line sample):
`ok: [ten.bruggerink.com] => (item=http://geolite.maxmind.com/download/geoip/database/GeoLiteCountry/GeoIP.dat.gz) => {"changed": false, "dest": "/var/maxmind/download/GeoIP.dat.gz", "gid": 0, "group": "root", "item": "http://geolite.maxmind.com/download/geoip/database/GeoLiteCountry/GeoIP.dat.gz", "mode": "0444", "msg": "file already exists", "owner": "root", "size": 711428, "state": "file", "uid": 0, "url": "http://geolite.maxmind.com/download/geoip/database/GeoLiteCountry/GeoIP.dat.gz"}`
And in the gunzip task I see:
`ok: [ten.bruggerink.com] => (item=GeoIP.dat) => {"changed": false, "cmd": "gunzip /var/maxmind/download/GeoIP.dat.gz", "item": "GeoIP.dat", "rc": 0, "stdout": "skipped, since /var/maxmind/GeoIP.dat exists", "stdout_lines": ["skipped, since /var/maxmind/GeoIP.dat exists"]}
ok: [ten.bruggerink.com] => (item=GeoIPv6.dat) => {"changed": false, "cmd": "gunzip /var/maxmind/download/GeoIPv6.dat.gz", "item": "GeoIPv6.dat", "rc": 0, "stdout": "skipped, since /var/maxmind/GeoIPv6.dat exists", "stdout_lines": ["skipped, since /var/maxmind/GeoIPv6.dat exists"]}`
I am new to Travis-CI, so I would welcome any thoughts on the source of any differences between the image it is building and my dev system. In the mean time, I will try playing around with the tasks and see if I can get them to behave consistently.

**Comment by drzow** [comment]
Ah-ha: think I found the difference. That of course being that the CI environment gets reset on every run. Testing my fix now; hopefully have update in the morning.

**Comment by drzow** [comment]
Looks like that did it!

**Comment by juju4** [comment]
Currently, I mostly rely on travis, but each role has also vagrant and kitchen-test that can help for future case (multiple backends, often different issues to found)

Seems perfect to me! Thanks a lot!

**Pull request merged**
